//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrudPart2.Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class profile
    {
        public int ID { get; set; }
        [Required(ErrorMessage ="Name cannot be null")]
        public string Name { get; set; }
        [Required(ErrorMessage ="Email cannot be null")]
        [EmailAddress]
        public string Email { get; set; }
        [Required(ErrorMessage ="Address cannot be null")]
        public string Address { get; set; }
    }
}
